### ISSUE TITLE
Inconsistent geolocation format

### ISSUE THREAD

**Issue by hearvox** [TowCenter/partisan-local-news#1]
Thanks so much for compiling this list. I wanted to alert you to some differing geolocation formats for the same entity in  [/datasets/domains/all_domains.csv](https://github.com/TowCenter/partisan-local-news/blob/main/datasets/domains/all_domains.csv).

The bulk of your states have their full name, but these few use the abbreviation:
```
107	Natural State Business News	AR
748	New Mexico Sun	NM
1068	Texas Realty News	TX
```

And these another format:
```
976	McHenry Times	State: Illinois
977	West Loop Today	State: Illinois
978	Louisiana Record	State: Louisiana
979	St. Louis Record	State: Missouri
```

Also, all United States geolocations use "US", except for:
```
256	Insurance Rate Reporter	Country: US
257	Legal Newsline	Country: US
258	Flexible Work News	country:US
```

These are duplicates:
```
1095	Interior Newswire	US	interiornewswire.com
1110	Interior Newswire	US	interiornewswire.com
```

And this value has a trailing whitespace, i.e., "The Record, Inc. "
`892	The Record, Inc.`

**Comment by anothercookiecrumbles** [comment]
Thanks for flagging this, Barrett. Will fix asap.

**Comment by anothercookiecrumbles** [comment]
Fixed.

**Comment by hearvox** [comment]
Pri, that was quick. Thx. I'll be adding your new data to our Pink Slime map/table soon: https://iffy.news/pink-slime-fake-local-news/
